/*
 * Defines actions.
 */

const constants = {
  INIT_PLUGINS: 'INIT_PLUGINS',
  SET_APP_DB: 'SET_APP_DB',
  SET_NEO_DATASETS: 'SET_NEO_DATASETS',
  SET_NEO_SERVER: 'SET_NEO_SERVER',
  SET_NEO_MESHINFO: 'SET_NEO_MESHINFO',
  UPDATE_RESULTS: 'UPDATE_RESULTS',
  CLEAR_RESULT: 'CLEAR_RESULT',
  CLEAR_NEW_RESULT: 'CLEAR_NEW_RESULT',
  UPDATE_QUERY: 'UPDATE_QUERY',
  APP_SET_SELECTED_RESULT: 'APP_SET_SELECTED_RESULT',
  LOGIN_USER: 'LOGIN_USER',
  SET_USER_TOKEN: 'SET_USER_TOKEN',
  LOGOUT_USER: 'LOGOUT_USER',
  AUTH_ERROR: 'AUTH_ERROR',
  META_INFO_ERROR: 'META_INFO_ERROR',
  API_ERROR: 'API_ERROR',
  PLUGIN_SUBMITTING: 'PLUGIN_SUBMITTING',
  PLUGIN_SAVE_RESPONSE: 'PLUGIN_SAVE_RESPONSE',
  PLUGIN_CACHE_HIT: 'PLUGIN_CACHE_HIT',
  PLUGIN_SUBMIT_ERROR: 'PLUGIN_SUBMIT_ERROR',
  PLUGIN_RESPONSE_ERROR: 'PLUGIN_RESPONSE_ERROR',
  INIT_VIEWPLUGINS: 'INIT_VIEWPLUGINS',
  SKELETON_ADD_ID: 'SKELETON_ADD_ID',
  SKELETON_REMOVE: 'SKELETON_REMOVE',
  SET_FULLSCREEN_VIEWER: 'SET_FULLSCREEN_VIEWER',
  CLEAR_FULLSCREEN_VIEWER: 'CLEAR_FULLSCREEN_VIEWER',
  CLEAR_ERRORS: 'CLEAR_ERRORS',
  CLEAR_NOTIFICATION: 'CLEAR_NOTIFICATION',
  NOTIFICATION: 'NOTIFICATION',
  NEUROGLANCER_ADD_ID: 'NEUROGLANCER_ADD_ID',
};
export default constants;
