/*
 * Defines actions.
*/ 

"use strict"; 

const constants = {
    INIT_PLUGINS : 'INIT_PLUGINS',
    SET_APP_DB : 'SET_APP_DB',
    SET_URL_QS: 'SET_URL_QS',
    ACTIVATE_PLUGIN: 'ACTIVATE_PLUGIN',
    DEACTIVATE_PLUGIN: 'DEACTIVATE_PLUGIN',
    SET_NEO_DATASETS: 'SET_NEO_DATASETS',
    SET_NEO_SERVER: 'SET_NEO_SERVER',
    UPDATE_QUERY: 'UPDATE_QUERY',
    SET_QUERY_STATUS: 'SET_QUERY_STATUS',
    SET_NEO_ERROR: 'SET_NEO_ERROR',
    FINISH_QUERY: 'FINISH_QUERY',
    UPDATE_RESULTS: 'UPDATE_RESULTS',
    APPEND_RESULTS: 'APPEND_RESULTS',
    CLEAR_RESULT: 'CLEAR_RESULT',
    LOGIN_USER: 'LOGIN_USER',
    SET_USER_TOKEN: 'SET_USER_TOKEN',
    LOGOUT_USER: 'LOGOUT_USER',
}
export default constants
